FROM alpine:3.4

RUN echo "===> Adding dependency..." \
    && apk add --update geoip bash tar \
    && rm -rf /var/cache/apk/*

COPY heka-0_10_0-linux-amd64.tar.gz entrypoint.sh /
RUN tar zxvf heka-0_10_0-linux-amd64.tar.gz -C /usr --strip=1 \
    && cp /usr/share/heka/examples/hekad.toml /etc/hekad.toml \
    && rm /heka-0_10_0-linux-amd64.tar.gz

VOLUME ["/var/heka/input", "/var/heka/run", "/usr/share/heka/local"]
CMD ["/entrypoint.sh"]
